# Generated by Django 3.1.7 on 2021-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210320_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Суперпользователь с таким именем уже существует.'}, help_text='Максимальные длина 15 символов. Можно использовать @/./+/-/_', max_length=15, unique=True, verbose_name='Admin_name'),
        ),
    ]
