# Generated by Django 3.2.3 on 2021-05-31 08:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210320_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Пользователь с таким телефоном уже существует.'}, max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
