# Generated by Django 3.2.3 on 2021-11-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20211116_1319'),
        ('user', '0019_auto_20211116_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cart', verbose_name='Корзина'),
        ),
    ]
