# Generated by Django 3.2.3 on 2021-11-17 19:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Пользователь с таким телефоном уже существует.'}, max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
