# Generated by Django 3.1.5 on 2021-02-07 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='sneakers_logos', verbose_name='Фотография')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('img_detail', models.FileField(upload_to='sneakers_img', verbose_name='Фотографии модели')),
                ('description', models.TextField(verbose_name='Описание вещи')),
                ('back', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_backs', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Все кроссовки',
                'verbose_name_plural': 'Кроссовки',
            },
        ),
    ]
