# Generated by Django 3.1.7 on 2021-03-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='sneakers_logos', verbose_name='Фотография')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание вещи')),
            ],
            options={
                'verbose_name': 'Все кроссовки',
                'verbose_name_plural': 'Кроссовки',
            },
        ),
        migrations.CreateModel(
            name='ArticlesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_detail', models.ImageField(upload_to='sneakers_img', verbose_name='Фотографии модели')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.articles')),
            ],
            options={
                'verbose_name': 'Фотография модели',
                'verbose_name_plural': 'Фотографии модели кроссовок',
            },
        ),
    ]
