# Generated by Django 3.2.3 on 2021-10-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Цена')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.articles')),
            ],
            options={
                'verbose_name': 'Размер модели',
                'verbose_name_plural': 'Размеры моделей',
            },
        ),
    ]
