# Generated by Django 3.1.5 on 2021-02-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210204_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(upload_to='sneakers_logos', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img_detail',
            field=models.FileField(upload_to='sneakers_logos_details', verbose_name='Фотографии модели'),
        ),
    ]
