# Generated by Django 3.1.5 on 2021-02-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210207_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img_detail',
            field=models.FileField(upload_to='sneakers_logos_details/', verbose_name='Фотографии модели'),
        ),
    ]
