# Generated by Django 3.1.5 on 2021-02-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_articles_img_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img_detail',
            field=models.FileField(default=1, upload_to='sneakers_img', verbose_name='Фотографии модели'),
            preserve_default=False,
        ),
    ]
