# Generated by Django 3.1.5 on 2021-02-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_articles_img_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img_detail',
            field=models.FileField(max_length=5, upload_to='sneakers_img', verbose_name='Фотографии модели'),
        ),
    ]
