# Generated by Django 3.1.5 on 2021-02-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210207_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img_detail',
            field=models.ImageField(max_length=5, upload_to='sneakers_img', verbose_name='Фотографии модели'),
        ),
    ]
