# Generated by Django 3.1.5 on 2021-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210207_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
        migrations.AlterField(
            model_name='articles',
            name='img_detail',
            field=models.FileField(upload_to='sneakers_img', verbose_name='Фотографии модели'),
        ),
    ]
