# Generated by Django 3.1.5 on 2021-02-07 16:12

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('catalog', '0009_auto_20210207_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Все кроссовки', 'verbose_name_plural': 'Кроссовки'},
        ),
        migrations.AddField(
            model_name='articles',
            name='cover',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gdgd', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
    ]
