# Generated by Django 3.1.5 on 2021-02-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210207_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='cover',
        ),
    ]
