# Generated by Django 3.1.5 on 2021-02-07 16:27

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('catalog', '0011_remove_articles_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='back',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_backs', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
