# Generated by Django 3.1.5 on 2021-02-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_articles_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='back',
        ),
    ]
