# Generated by Django 3.1.5 on 2021-02-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_articles_back'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='img_detail',
        ),
        migrations.CreateModel(
            name='ArticlesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_detail', models.FileField(upload_to='sneakers_img', verbose_name='Фотографии модели')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.articles')),
            ],
            options={
                'verbose_name': 'Все кроссовки',
                'verbose_name_plural': 'Кроссовки',
            },
        ),
    ]
