# Generated by Django 3.1.5 on 2021-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210207_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Все кроссовки', 'verbose_name_plural': 'Кроссовки'},
        ),
        migrations.AlterModelOptions(
            name='articlesimage',
            options={'verbose_name': 'Фотография модели', 'verbose_name_plural': 'Фотографии модели кроссовок'},
        ),
        migrations.AlterField(
            model_name='articlesimage',
            name='img_detail',
            field=models.ImageField(upload_to='sneakers_img', verbose_name='Фотографии модели'),
        ),
    ]
